name: Auto-Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          repository: your-username/repo-name
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/Aivankun/Project-X-Front-End-Latest.git
          git fetch upstream
          git checkout main
          git merge upstream/main
      
      - name: Push Changes to Fork
        run: |
          git push origin main

