name: Sync main from upstream

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:         #  Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/Aivankun/Project-X-Front-End-Latest.git
          git fetch upstream

      - name: Merge upstream/main into fork/main
        run: |
          git merge --no-edit upstream/main || echo "No changes to merge"

      - name: Check for changes and push
        run: |
          if [ "$(git status --porcelain)" ]; then
            git push origin main
            echo "Changes pushed to the main branch"
          else
            echo "No changes to push"
          fi
