import { useMemo } from "react";

const labels = {
  English: {
    Dashboard: "Dashboard",
    ManageTrackResponse: "Manage and track your reference response",
    StartReferenceCheck: "Start Reference Check",
    ActiveJobs: "Active Jobs",
    PendingReferences: "Pending References",
    CompletedReferences: "Completed References",
    TotalApplicants: "Total Applicants",
    ReferenceOverview: "Reference Overview",
    ByDepartment: "By Department",
    RecentActivities: "Recent Activities",
    ClickToStart: "Click here to begin the reference check process.",
    ManageTrackProcesses: "Manage and track your reference check processes.",
    completed: "completed",
    NoRecentActivities: "No recent activities",
    ViewAll: "View All",
    ShowLess: "Show Less",
    departments: {
      sales: "Sales",
      marketing: "Marketing",
      customerService: "Customer Service",
      hr: "Human Resources (HR)",
      finance: "Finance",
      accounting: "Accounting",
      operations: "Operations",
      it: "IT (Information Technology)",
      legal: "Legal",
      administration: "Administration",
      productDevelopment: "Product Development",
      rAndD: "Research and Development (R&D)",
      logistics: "Logistics, Supply Chain & Procurement",
      businessDev: "Business Development",
      pr: "Public Relations (PR)",
      design: "Design",
      compliance: "Compliance",
      riskManagement: "Risk Management",
    },
    Total: "Total",
    Complete: "Complete",
    months: {
      January: "January",
      February: "February",
      March: "March",
      April: "April",
      May: "May",
      June: "June",
      July: "July",
      August: "August",
      September: "September",
      October: "October",
      November: "November",
      December: "December",
    },
    "a reference check for": "a reference check for",
    ago: "ago",
    TotalCredits: "Total Credits",
    TotalRate: "Total Rate",
    AcceptanceRate: "Acceptance Rate",
  },
  Japanese: {
    Dashboard: "ダッシュボード",
    ManageTrackResponse: "リファレンスチェックの管理と追跡",
    StartReferenceCheck: "リファレンスチェックを開始する",
    ActiveJobs: "求人",
    PendingReferences: "保留中のリファレンス",
    CompletedReferences: "完了リファレンス",
    TotalApplicants: "応募者数",
    ReferenceOverview: "リファレンスチェック概要",
    ByDepartment: "部門別",
    RecentActivities: "最近の活動",
    ClickToStart:
      "ここをクリックしてリファレンスチェックプロセスを開始します。",
    ManageTrackProcesses: "リファレンスチェックプロセスを管理し、追跡します。",
    completed: "完了",
    NoRecentActivities: "最近の活動はありません",
    ViewAll: "すべて表示",
    ShowLess: "表示を減らす",
    departments: {
      sales: "営業",
      marketing: "マーケティング",
      customerService: "カスタマーサービス",
      hr: "人事",
      finance: "財務",
      accounting: "経理",
      operations: "運営",
      it: "IT",
      legal: "法務",
      administration: "総務",
      productDevelopment: "製品開発",
      rAndD: "研究開発",
      logistics: "物流・調達",
      businessDev: "事業開発",
      pr: "広報",
      design: "デザイン",
      compliance: "コンプライアンス",
      riskManagement: "リスク管理",
    },
    Total: "合計",
    Complete: "完了",
    months: {
      January: "1月",
      February: "2月",
      March: "3月",
      April: "4月",
      May: "5月",
      June: "6月",
      July: "7月",
      August: "8月",
      September: "9月",
      October: "10月",
      November: "11月",
      December: "12月",
    },
    "a reference check for": "のリファレンスチェック",
    ago: "前",
    TotalCredits: "総クレジット",
    TotalRate: "総レート",
    AcceptanceRate: "承認率",
  },
};

export const useLabels = (language = "English") => {
  const currentLabels = useMemo(() => {
    return labels[language] || labels.English;
  }, [language]);

  return {
    labels: currentLabels,
  };
};
